insert into public.site_settings (key, value, is_public)
values ('home_hero', '{"lineOneBefore":"لا نلاحق ","highlight":"الاتجاه","lineOneAfter":".","lineTwo":"نصنعه.","ctaLabel":"لنتحدث","metaTop":"Sharks Agency","metaLocation":"Palestine","metaServices":"Creative / Strategy / Digital","directionLabel":"Selected — Creative Direction","scrollLabel":"Scroll"}'::jsonb, true)
on conflict (key) do update set value = excluded.value, is_public = excluded.is_public;

insert into public.site_settings (key, value, is_public)
values ('studio', '{"titleBefore":"ننظر إلى المشروع كمنظومة ","titleHighlight":"متكاملة","titleAfter":".","description":"نبحث، نفهم، نحدّد الاتجاه، ثم نبني ما يحتاجه المشروع فعلًا.","trackSummary":"مسارات تعمل كمنظومة واحدة.","eyebrow":"The Studio","label":"الاستوديو","tracks":["Strategy","Creative","Marketing","Digital"]}'::jsonb, true)
on conflict (key) do update set value = excluded.value, is_public = excluded.is_public;

insert into public.site_settings (key, value, is_public)
values ('editorial', '{"services":{"eyebrow":"What We Do","label":"خدماتنا","firstLine":"لا نقدّم قائمة خدمات.","before":"نبني ","highlight":"المنظومة","after":" التي يحتاجها المشروع."},"scenarios":{"eyebrow":"Capabilities in Action","before":"كيف ","highlight":"نتحرك","after":"؟","description":"ليست أعمالًا سابقة، بل سيناريوهات تكشف طريقة تفكيرنا في التحديات.","cta":"كيف نتعامل معها؟"},"process":{"label":"كيف نتحرك؟","steps":[{"no":"01","title":"نكتشف ونفهم","desc":"نغوص في السوق والجمهور والمنافسة قبل أن نرسم أي خط."},{"no":"02","title":"نحدّد ونبني","desc":"نحوّل الفهم إلى اتجاه واضح، ثم نبني المنظومة حوله."},{"no":"03","title":"نطلق ونتطوّر","desc":"ندفع العمل إلى السوق، ونقرأ الأثر، ونصقل الحركة."}]},"philosophy":{"eyebrow":"Sharks Move Forward.","firstLine":"لا ننتظر الموجة.","before":"نحدّد ","highlight":"اتجاهها","after":"."},"kinetic":{"eyebrow":"Capabilities — In Motion","words":["استراتيجية","هوية","إبداع","محتوى","تسويق","تجارب رقمية"]},"capabilities":{"eyebrow":"Where We Can Make a Difference","before":"مساحات نعرف كيف ","highlight":"نتحرك","after":" فيها.","description":"نعرف أين يمكن أن نصنع فرقًا — لا من نلاحقه، بل ما نجيد بناءه.","items":[{"ar":"الشركات الناشئة","en":"Startups"},{"ar":"العلامات المحلية","en":"Local Brands"},{"ar":"التجارة الإلكترونية","en":"E-commerce"},{"ar":"المنتجات الرقمية","en":"Digital Products"},{"ar":"الضيافة","en":"Hospitality"},{"ar":"التجزئة","en":"Retail"},{"ar":"الثقافة","en":"Culture"},{"ar":"الأعمال النامية","en":"Growing Businesses"}]},"blog":{"eyebrow":"Sharks Journal","label":"المدونة","before":"نكتب عن الأشياء التي تغيّر ","highlight":"الاتجاه","after":".","topics":["Strategy","Design","Branding","Digital","Culture"],"allTitle":"كل المقالات","emptyMessage":"نجهّز مقالات تستحق القراءة. عد قريبًا.","breakWords":["نفكّر.","نكتب.","نختبر."],"breakBefore":"ثم نغيّر ","breakHighlight":"الاتجاه","breakAfter":"."},"navigation":[{"label":"الرئيسية","href":"/","match":"/"},{"label":"أعمالنا","href":"/#work","match":"/approach","sectionId":"work"},{"label":"خدماتنا","href":"/#services","sectionId":"services"},{"label":"الاستوديو","href":"/studio","match":"/studio","sectionId":"studio"},{"label":"المدونة","href":"/blog","match":"/blog"}],"copyright":"All rights reserved","routeSeo":{"studio":{"title":"الاستوديو","description":"كيف يفكر استوديو Sharks Agency، وكيف تتحرك مساراته كمنظومة واحدة."},"contact":{"title":"تواصل معنا","description":"ابدأ حديثًا مع Sharks Agency حول مشروعك واتجاهه القادم."},"blog":{"title":"المدونة","description":"Sharks Journal — أفكار عن الاستراتيجية والهوية والتصميم والتسويق والويب.","ogTitle":"Sharks Journal","ogDescription":"نكتب عن الأشياء التي تغيّر الاتجاه."},"works":{"title":"أعمالنا","description":"مختارات من أعمال Sharks Agency."}}}'::jsonb, true)
on conflict (key) do update set value = excluded.value, is_public = excluded.is_public;
