-- Existing media objects are backed up independently from SQL migrations.

update public.services set image_url = 'services/content-and-digital-experiences.jpg' where slug = 'content-and-digital-experiences';

update public.services set image_url = 'services/identity-and-creativity.jpg' where slug = 'identity-and-creativity';

update public.services set image_url = 'services/marketing-and-communication.jpg' where slug = 'marketing-and-communication';

update public.services set image_url = 'services/strategy-and-growth.jpg' where slug = 'strategy-and-growth';

update public.scenarios set cover_image_url = 'scenarios/from-chaos-to-system.jpg', og_image_url = 'scenarios/from-chaos-to-system.jpg' where slug = 'from-chaos-to-system';

update public.scenarios set cover_image_url = 'scenarios/from-product-to-experience.jpg', og_image_url = 'scenarios/from-product-to-experience.jpg' where slug = 'from-product-to-experience';

update public.scenarios set cover_image_url = 'scenarios/from-idea-to-brand.jpg', og_image_url = 'scenarios/from-idea-to-brand.jpg' where slug = 'from-idea-to-brand';

update public.blog_posts set cover_image_url = 'blog/identity-does-not-start-with-logo.jpg', og_image_url = 'blog/identity-does-not-start-with-logo.jpg', content = '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"حين يطلب عميل «هوية جديدة»، يكون الشعار غالبًا أول ما يخطر في ذهنه. لكن الشعار مجرد ختمٍ يُوضع في النهاية على قرارٍ اتُّخذ قبله بوقت طويل. الهوية الحقيقية تسبق الشكل: إنها الموقف الذي تتبناه العلامة، والصوت الذي تتحدث به، والاتجاه الذي تسير فيه."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"الشكل نتيجة، لا نقطة بداية"}]},{"type":"paragraph","content":[{"type":"text","text":"عندما نبدأ من الشعار، نصمم غلافًا لكتابٍ لم يُكتب بعد. النتيجة شعار جميل ربما، لكنه معلّق في الفراغ — لا يستند إلى معنى، ولا يقاوم الزمن. أما حين نبدأ من فهم العلامة، فإن كل قرار بصري يصبح امتدادًا طبيعيًا لموقفٍ واضح."}]},{"type":"blockquote","attrs":{},"content":[{"type":"paragraph","content":[{"type":"text","text":"الهوية ليست شكلًا. إنها قرار."}]}]},{"type":"paragraph","content":[{"type":"text","text":"قبل أن نرسم أي خط، نسأل: لمن نتحدث؟ وبماذا نختلف؟ وما الشعور الذي نريد أن نتركه؟ هذه الأسئلة لا تُجاب بالألوان، بل بالاستراتيجية. والتصميم الجيد لا يخترع هذه الإجابات، بل يجعلها مرئية."}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"ما الذي يسبق الرسم؟"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"فهم واضح للسوق والمنافسة وموقع العلامة داخلها."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"تعريف دقيق للجمهور: من يهمّنا، ومن لا يهمّنا."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"صوتٌ ونبرة يمكن الالتزام بهما عبر كل نقطة تواصل."}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"قرار حول ما تريد العلامة أن تُعرف به — وما ترفض أن تكونه."}]}]}]},{"type":"image","attrs":{"src":"blog/beautiful-vs-clear.jpg","caption":"الهوية نظام متكامل، لا رمز منفرد.","alt":"الهوية نظام متكامل، لا رمز منفرد.","fullWidth":true}},{"type":"sharksHighlight","content":[{"type":"text","text":"الشعار الذي يبدأ من معنى واضح يصمد. الشعار الذي يبدأ من الذوق وحده يتقادم."}]},{"type":"paragraph","content":[{"type":"text","text":"حين نصل أخيرًا إلى الشعار، لا يكون خيارًا عشوائيًا بين مقترحات، بل خلاصةً حتمية لكل ما سبقه. عندها فقط يصبح الشعار قويًا — لأنه يحمل قرارًا، لا مجرد شكل."}]}]}'::jsonb where slug = 'identity-does-not-start-with-logo';

update public.blog_posts set cover_image_url = 'blog/market-needs-direction.jpg', og_image_url = 'blog/market-needs-direction.jpg', content = '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"حين يشتد التنافس، يكون رد الفعل الأول عادةً هو رفع الصوت: مزيد من الإعلانات، مزيد من المحتوى، مزيد من الحضور. لكن السوق لا يعاني من نقص الأصوات، بل من فائضها. ما يندر فعلًا هو الوضوح."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"لماذا يفشل الصوت الأعلى؟"}]},{"type":"paragraph","content":[{"type":"text","text":"الصوت الأعلى يلفت الانتباه لحظة، ثم يذوب في الضجيج العام. أما الاتجاه الواضح فيبني ذاكرة. حين يعرف الناس ما تمثّله علامتك، لا يحتاجون إلى تذكيرٍ دائم بوجودها."}]},{"type":"blockquote","attrs":{},"content":[{"type":"paragraph","content":[{"type":"text","text":"لا ننتظر الموجة. نحدّد اتجاهها."}]}]},{"type":"sharksHighlight","content":[{"type":"text","text":"الوضوح يوفّر عليك ميزانية الصراخ. حين يعرف الناس اتجاهك، يتذكرونك دون أن تلاحقهم."}]},{"type":"paragraph","content":[{"type":"text","text":"الاتجاه الواضح قرار صعب لأنه يعني الاختيار: أن تقول لا لجماهير، ولأسواق، ولفرصٍ لامعة لكنها خارج المسار. غير أن هذا الرفض نفسه هو ما يمنح العلامة حدّتها."}]}]}'::jsonb where slug = 'market-needs-direction';

update public.blog_posts set cover_image_url = 'blog/when-simplicity-is-bad.jpg', og_image_url = 'blog/when-simplicity-is-bad.jpg', content = '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"صارت «البساطة» كلمة سحرية في التصميم. لكن حين تتحول إلى شعارٍ نُطبّقه دون تفكير، تصبح غطاءً للكسل: نحذف التفاصيل لأنها صعبة، لا لأنها زائدة."}]},{"type":"blockquote","attrs":{},"content":[{"type":"paragraph","content":[{"type":"text","text":"البساطة الجيدة توضيح. البساطة السيئة حذف."}]}]},{"type":"paragraph","content":[{"type":"text","text":"الفرق بينهما دقيق: البساطة الحقيقية تزيل ما يشوّش على المعنى، أما التبسيط المفرط فيزيل المعنى نفسه. الأولى تتطلب فهمًا عميقًا، والثانية تتهرّب منه."}]},{"type":"sharksHighlight","content":[{"type":"text","text":"اسأل دائمًا: هل أزلت التعقيد، أم أخفيته على حساب المستخدم؟"}]}]}'::jsonb where slug = 'when-simplicity-is-bad';

update public.blog_posts set cover_image_url = 'blog/ai-and-creativity.jpg', og_image_url = 'blog/ai-and-creativity.jpg', content = '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"كلما ظهرت أداة جديدة، عاد السؤال نفسه: هل ستقتل الإبداع؟ لكن الأدوات لا تصنع الاتجاه، بل تنفّذه بسرعة أكبر. والذكاء الاصطناعي، مثل كل أداة قوية، يضخّم ما لديك — لا يخلقه من عدم."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"ما الذي يكشفه؟"}]},{"type":"paragraph","content":[{"type":"text","text":"حين يصبح التنفيذ رخيصًا وسريعًا، تفقد المهارة التقنية وحدها قيمتها التنافسية. ويبقى السؤال الأصعب: ماذا تريد أن تقول؟ ولماذا؟ هنا يظهر الفرق بين من يملك رؤية ومن يجيد التنفيذ فقط."}]},{"type":"blockquote","attrs":{},"content":[{"type":"paragraph","content":[{"type":"text","text":"الأداة تسرّع الطريق. لكنها لا تختار الوجهة."}]}]},{"type":"sharksHighlight","content":[{"type":"text","text":"الذكاء الاصطناعي لا يعوّض غياب الفكرة. إنه يجعل غيابها أكثر وضوحًا."}]},{"type":"paragraph","content":[{"type":"text","text":"المبدع الذي يعرف اتجاهه سيستخدم هذه الأدوات ليذهب أبعد. أما من لا يملك اتجاهًا، فسيصنع بها المزيد من اللاشيء — أسرع."}]}]}'::jsonb where slug = 'ai-and-creativity';

update public.blog_posts set cover_image_url = 'blog/design-as-growth-tool.jpg', og_image_url = 'blog/design-as-growth-tool.jpg', content = '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"يُعامَل التصميم أحيانًا كطبقة تجميلية تُضاف في النهاية. لكن التصميم الأقوى يبدأ مبكرًا، ويُتخذ كقرارٍ تجاري: كيف نجعل المنتج أوضح، والقرار أسهل، والثقة أسرع؟"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"من الشكل إلى الأثر"}]},{"type":"paragraph","content":[{"type":"text","text":"حين نربط كل قرار تصميمي بهدف — تحويل، احتفاظ، وضوح، ثقة — يتوقف التصميم عن كونه مسألة ذوق، ويصبح رافعة نمو قابلة للقياس."}]},{"type":"blockquote","attrs":{},"content":[{"type":"paragraph","content":[{"type":"text","text":"التصميم الجيد لا يُرى فقط. يُحدث فرقًا يمكن قياسه."}]}]},{"type":"sharksHighlight","content":[{"type":"text","text":"اسأل عن كل عنصر: ما القرار الذي يسهّله على المستخدم؟ إن لم تكن هناك إجابة، فهو زينة."}]}]}'::jsonb where slug = 'design-as-growth-tool';

update public.blog_posts set cover_image_url = 'blog/same-websites.jpg', og_image_url = 'blog/same-websites.jpg', content = '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"افتح عشرة مواقع لشركاتٍ في المجال نفسه، وستجد الترتيب نفسه تقريبًا: عنوان كبير، زر، ثلاث بطاقات، شهادات عملاء، تذييل. ليس لأن هذا هو الأفضل، بل لأنه الأكثر أمانًا."}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"التشابه قرار، لا قدر"}]},{"type":"paragraph","content":[{"type":"text","text":"حين ينسخ الجميع القالب نفسه خوفًا من المخاطرة، يصبح التميّز نفسه مخاطرة. لكن الموقع الذي يشبه كل شيء لا يُتذكر بأي شيء."}]},{"type":"sharksHighlight","content":[{"type":"text","text":"إذا كان تصميمك يمكن أن ينتمي لأي شركة، فهو لا ينتمي لك."}]},{"type":"paragraph","content":[{"type":"text","text":"الخروج من التشابه لا يعني الغرابة، بل الوضوح: أن يعكس الموقع اتجاه العلامة الحقيقي، لا القالب الأكثر شيوعًا."}]}]}'::jsonb where slug = 'same-websites';

update public.blog_posts set cover_image_url = 'blog/beautiful-vs-clear.jpg', og_image_url = 'blog/beautiful-vs-clear.jpg', content = '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"من السهل أن تصنع شيئًا جميلًا. الأصعب أن تصنع شيئًا واضحًا. الجمال يلفت الانتباه، لكن الوضوح هو ما يبني الفهم والثقة على المدى الطويل."}]},{"type":"blockquote","attrs":{},"content":[{"type":"paragraph","content":[{"type":"text","text":"الجميل يُعجب. الواضح يُفهم — ويُتذكر."}]}]},{"type":"paragraph","content":[{"type":"text","text":"حين تتعارض الاثنتان، نختار الوضوح. لأن علامة يفهمها الناس بسرعة أقوى من علامة يعجبون بها ثم ينسونها."}]},{"type":"sharksHighlight","content":[{"type":"text","text":"الوضوح ليس عدو الجمال. إنه ما يمنحه معنى."}]}]}'::jsonb where slug = 'beautiful-vs-clear';
